void treeviewer() {
//=========Macro generated by ROOT version6.02/05
//=========for tree "tree1" (Wed May 13 18:34:15 2015)
//===This macro can be opened from a TreeViewer session after loading
//===the corresponding tree, or by running root with the macro name argument

   open_session();
}

open_session(void *p = 0) {
   gSystem->Load("libTreeViewer");
   TTreeViewer *treeview = (TTreeViewer *) p;
   if (!treeview) treeview = new TTreeViewer();
   TTree *tv_tree = (TTree*)gROOT->FindObject("tree1");
   TFile *tv_file = (TFile*)gROOT->GetListOfFiles()->FindObject("experiment.root");
   if (!tv_tree) {
      if (!tv_file) tv_file = new TFile("experiment.root");
      if (tv_file)  tv_tree = (TTree*)tv_file->Get("tree1");
      if(!tv_tree) {
         printf("Tree %s not found", fTree->GetName());
         return;
      }
   }

   treeview->SetTreeName("tree1");
   treeview->SetNexpressions(10);
//         Set expressions on axis and cut
   TTVLVEntry *item;
//   X expression
   item = treeview->ExpressionItem(0);
   item->SetExpression("", "-empty-");
//   Y expression
   item = treeview->ExpressionItem(1);
   item->SetExpression("", "-empty-");
//   Z expression
   item = treeview->ExpressionItem(2);
   item->SetExpression("", "-empty-");
//   Cut expression
   item = treeview->ExpressionItem(3);
   item->SetExpression("zv<20", "~cut");
//         Scan list
   item = treeview->ExpressionItem(4);
   item->SetExpression("chi2:atan2(sqrt(px*px+py*py),pz)", "Scan box");
//         User defined expressions
   item = treeview->ExpressionItem(5);
   item->SetExpression("sqrt(px*px+py*py)", "~pt", kFALSE);
   item = treeview->ExpressionItem(6);
   item->SetExpression("atan2(~pt,pz)", "~theta", kFALSE);
   item = treeview->ExpressionItem(7);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(8);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(9);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(10);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(11);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(12);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(13);
   item->SetExpression("", "-empty-", kFALSE);
   item = treeview->ExpressionItem(14);
   item->SetExpression("", "-empty-", kFALSE);
//--- session object
   tv_session = new TTVSession(treeview);
   treeview->SetSession(tv_session);
//--- Connect first record
   tv_session->First();
}
